route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram'

  routes:
    - receiver: "telegram"
      group_wait: 10s
      match_re:
        severity: critical
      continue: true

    - receiver: "telegramw"
      group_wait: 10s
      match_re:
        severity: warning
      continue: true

receivers:
  - name: 'telegram'
    telegram_configs:
    - bot_token: 'A'
      api_url: 'https://api.telegram.org'
      chat_id: -AA
      parse_mode: ''
      message: "🚨 Alertmanager 🚨\n--\n🔺 Alertname: {{ .GroupLabels.alertname}}\n🔺 Severity: {{ .CommonLabels.severity }}\n📌 {{ range .Alerts }}{{ .Annotations.summary }}\n{>

  - name: 'telegramw'
    telegram_configs:
    - bot_token: 'B'
      api_url: 'https://api.telegram.org'
      chat_id: -BB
      parse_mode: ''
      message: "🚨 wAlertmanager 🚨\n--\n🔺 Alertname: {{ .GroupLabels.alertname}}\n🔺 Severity: {{ .CommonLabels.severity }}\n📌 {{ range .Alerts }}{{ .Annotations.summary }}\n>
